import {NextRequest,NextResponse} from 'next/server';
import {createSession,readSession,updateSession} from '@/lib/server/db';
export const runtime='nodejs';
export const dynamic='force-dynamic';
import {dataService} from '@/lib/data/service';
import {GameState,Selection,normalize,seasonLabel,leagues,countries} from '@/lib/game/types';
import {guess,pickPlayer,publicGame} from '@/lib/game/engine';
const json=(v:unknown,status=200)=>NextResponse.json(v,{status,headers:{'Cache-Control':'no-store'}});
function owner(req:NextRequest){return req.cookies.get('kb_owner')?.value;}
async function session(req:NextRequest,id:string){const g=await readSession(id,owner(req)??'');if(!g)throw Error('This match has expired. Start a new game.');return g;}
export async function GET(req:NextRequest){try{const path=req.nextUrl.pathname;const {players,mode}=await dataService();
if(path==='/api/seasons')return json({dataMode:mode,seasons:Array.from({length:12},(_,i)=>{const s=seasonLabel(2026-i);return {name:s,available:players.some(p=>p.season===s)}}),count:new Set(players.map(p=>p.id)).size});
if(path==='/api/leagues'||path==='/api/countries'){const s=req.nextUrl.searchParams.get('season');const pool=players.filter(p=>s==='every'||p.season===s);const list=path.endsWith('leagues')?leagues.map(l=>({name:l.name,count:pool.filter(p=>p.league===l.name).length})):countries.map(c=>({name:c[0],count:pool.filter(p=>p.nationality===c[0]).length}));return json(list);}
if(path==='/api/players'){const q=normalize(req.nextUrl.searchParams.get('q')??'');if(q.length<1)return json([]);const unique=[...new Map(players.map(p=>[p.id,p])).values()];return json(unique.filter(p=>p.aliases.some(a=>normalize(a).includes(q))||normalize(p.name).includes(q)).slice(0,12).map(p=>({id:p.id,name:p.name})));}
if(path.startsWith('/api/game/'))return json(publicGame(await session(req,path.split('/').pop()!),mode));return json({error:'Not found'},404);
}catch(e){console.error('Game read failed',e);return json({error:e instanceof Error?e.message:'VAR check failed. Please retry.'},503);}}
export async function POST(req:NextRequest){try{const origin=req.headers.get('origin');if(origin&&(new URL(origin).host!==req.headers.get('host')||new URL(origin).protocol!==req.nextUrl.protocol))return json({error:'Invalid request origin'},403);const raw=await req.json();if(!raw||typeof raw!=='object')return json({error:'Invalid request'},400);const body=raw as Record<string,unknown>;const {players,mode}=await dataService();const path=req.nextUrl.pathname;
if(path==='/api/game/start'){const selection=body.selection as Selection;if(!selection||!['league','country'].includes(selection.mode)||!['every',...Array.from({length:12},(_,i)=>seasonLabel(2015+i))].includes(selection.season)||typeof selection.category!=='string')return json({error:'Choose a valid season and challenge.'},400);const pool=players.filter(p=>(selection.season==='every'||p.season===selection.season)&&(selection.mode==='league'?p.league:p.nationality)===selection.category);const recent=Array.isArray(body.recent)?body.recent.filter((x:unknown)=>typeof x==='string').slice(-20):[];const selectedSeason=selection.season==='every'?pickPlayer([...new Map(pool.map(p=>[p.season,p])).values()],[]).season:selection.season;const player=pickPlayer(pool.filter(p=>p.season===selectedSeason),recent);const g:GameState={id:crypto.randomUUID(),selection,player,stage:0,attempts:0,status:'playing',score:0,history:[],version:0,createdAt:Date.now()};const own=owner(req)??crypto.randomUUID();await createSession(g,own);const res=json(publicGame(g,mode));res.cookies.set('kb_owner',own,{httpOnly:true,sameSite:'lax',secure:req.nextUrl.protocol==='https:',path:'/',maxAge:31536000});return res;}
if(path==='/api/game/guess'){if(typeof body.sessionId!=='string'||typeof body.playerId!=='string')return json({error:'Select a player from the suggestions.'},400);const g=await session(req,body.sessionId);if(body.version!==g.version)return json({error:'Match updated. Please reload.',game:publicGame(g,mode)},409);const pick=players.find(p=>p.id===body.playerId);if(!pick)return json({error:'Select a valid player.'},400);let n;try{n=guess(g,pick)}catch(e){return json({error:(e as Error).message},400)}const updated=await updateSession(n,owner(req)??'',g.version);if(!updated)return json({error:'Match updated. Please reload.'},409);return json(publicGame(n,mode,n.status==='won'?'You got it!':n.status==='lost'?'That one was tough.':n.stage!==g.stage?'Next clue unlocked.':'Not quite. One more try.'));}return json({error:'Not found'},404);
}catch(e){console.error('Game action failed',e);return json({error:e instanceof Error?e.message:'VAR check failed. Please retry.'},503);}}
