"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Play,Volume2,VolumeX,Settings2,HelpCircle,Trophy,Globe2,Infinity as InfinityIcon,ChevronRight,Check,Copy,RotateCcw,Home,LoaderCircle,ShieldCheck,X,LockKeyhole,UserRound,Target,Flag,CalendarDays,Maximize2} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Switch} from '@/components/ui/switch';
import {Logo} from './Logo';
import {PlayerSearch,Candidate} from './PlayerSearch';
import {HintCard,ProgressBar,FlagMark,displayHint} from './HintCard';
import {PublicGame,Selection,leagues,countries} from '@/lib/game/types';
import {sound} from '@/lib/game/sound';
type Screen='home'|'season'|'mode'|'category'|'loading'|'game'|'result'|'error';
type Catalog={dataMode:string;seasons:{name:string;available:boolean}[];count:number};
async function api<T=PublicGame>(path:string,body?:unknown):Promise<T>{const r=await fetch(path,{signal:AbortSignal.timeout(15000),...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const d=await r.json() as T & {error?:string};if(!r.ok)throw Error(d.error??'VAR check failed. Please retry.');return d;}
function stored<T,>(k:string,f:T):T{try{const x=localStorage.getItem(k);return x?JSON.parse(x):f}catch{return f}}
function remember(k:string,v:unknown){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
export default function KnowBalledge(){const [screen,setScreen]=useState<Screen>('home'),[catalog,setCatalog]=useState<Catalog|null>(null),[selection,setSelection]=useState<Selection>({season:'2024/25',mode:'league',category:''}),[game,setGame]=useState<PublicGame|null>(null),[counts,setCounts]=useState<Record<string,number>>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[reset,setReset]=useState(0),[soundOn,setSoundOn]=useState(true),[reduced,setReduced]=useState(false),[imperial,setImperial]=useState(false),[settings,setSettings]=useState(false),[help,setHelp]=useState(false),[leave,setLeave]=useState<Screen|null>(null),[copied,setCopied]=useState(false),[best,setBest]=useState(0),[countedScore,setCountedScore]=useState(0),[imageFailed,setImageFailed]=useState(false);const lock=useRef(false),screenRef=useRef<Screen>('home');screenRef.current=screen;
const go=useCallback((s:Screen,id?:string)=>{setScreen(s);setError('');setNotice('');const path=s==='home'?'/':s==='season'?'/play':s==='mode'?'/play/mode':s==='category'?'/play/category':s==='game'?'/game/'+id:s==='result'?'/results/'+id:null;if(path&&location.pathname!==path)history.pushState({},'',path);window.scrollTo({top:0,behavior:'instant'});},[]);
async function loadCatalog(){try{setCatalog(await api<Catalog>('/api/seasons'));setError('')}catch{setError('VAR check failed. We couldn’t load the squads. Try again.')}}
useEffect(()=>{setSoundOn(stored('kb-sound',true));setReduced(stored('kb-motion',matchMedia('(prefers-reduced-motion: reduce)').matches));setImperial(stored('kb-imperial',false));setBest(stored('kb-best',0));setSelection(stored('kb-selection',{season:'2024/25',mode:'league',category:''}));void loadCatalog();const restore=async()=>{const path=location.pathname;if(/^\/(game|results)\//.test(path)){setScreen('loading');try{const g:PublicGame=await api('/api/game/'+path.split('/').pop());setGame(g);setSelection(g.selection);go(g.status==='playing'?'game':'result',g.id);}catch(e){setError((e as Error).message);setScreen('error')}}else setScreen(path==='/play'?'season':path==='/play/mode'?'mode':path==='/play/category'?'category':'home');};void restore();const pop=()=>{if(screenRef.current==='game'){history.go(1);setLeave('home')}else void restore()};window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop)},[go]);
useEffect(()=>{remember('kb-selection',selection)},[selection]);
useEffect(()=>{if(screen==='season'&&!catalog)void loadCatalog()},[screen]);
useEffect(()=>{if(screen!=='category')return;let live=true;setCounts({});setBusy(true);api<{name:string;count:number}[]>(`/api/${selection.mode==='league'?'leagues':'countries'}?season=${encodeURIComponent(selection.season)}`).then(d=>{if(live)setCounts(Object.fromEntries(d.map((x:{name:string;count:number})=>[x.name,x.count])))}).catch(e=>{if(live)setError(e.message)}).finally(()=>{if(live)setBusy(false)});return()=>{live=false}},[screen,selection.season,selection.mode]);
useEffect(()=>{const unload=(e:BeforeUnloadEvent)=>{if(screen==='game'){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',unload);return()=>window.removeEventListener('beforeunload',unload)},[screen]);
useEffect(()=>{if(screen!=='result'||!game)return;setImageFailed(false);setCountedScore(0);const newBest=Math.max(best,game.score);setBest(newBest);remember('kb-best',newBest);if(game.player){const recent=stored<string[]>('kb-recent',[]);remember('kb-recent',[...recent.filter(x=>x!==game.player!.id),game.player.id].slice(-20))}const start=performance.now();let frame:number;const tick=(t:number)=>{const p=reduced?1:Math.min(1,(t-start)/650);setCountedScore(Math.round(game.score*(1-(1-p)**3)));if(p<1)frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[screen,game?.id]);
function navigate(s:Screen){sound('click',soundOn);if(screen==='game')setLeave(s);else go(s)}
async function start(sel:Selection=selection){if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');setSelection(sel);go('loading');sound('click',soundOn);try{const g:PublicGame=await api('/api/game/start',{selection:sel,recent:stored('kb-recent',[])});setGame(g);setReset(n=>n+1);go('game',g.id);sound('hint',soundOn)}catch(e){setError((e as Error).message);setScreen('error')}finally{lock.current=false;setBusy(false)}}
async function submit(p:Candidate){if(!game||lock.current)return;lock.current=true;setBusy(true);setError('');try{const g:PublicGame=await api('/api/game/guess',{sessionId:game.id,playerId:p.id,version:game.version});setGame(g);setReset(n=>n+1);setNotice(g.message??'');sound(g.status==='won'?'win':g.stage!==game.stage?'hint':'wrong',soundOn);if(g.status!=='playing')go('result',g.id)}catch(e){setError((e as Error).message)}finally{setBusy(false);lock.current=false}}
useEffect(()=>{const ctx=(document as unknown as {modelContext?:{registerTool:(t:unknown,o:unknown)=>Promise<void>}}).modelContext;if(!ctx?.registerTool)return;const life=new AbortController();void Promise.resolve(ctx.registerTool({name:'read_match',description:'Read the visible game state and already unlocked clues. Never reveals hidden player information.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('read_match accepts an empty object.');return {screen,selection,game}}},{signal:life.signal})).catch(()=>{});return()=>life.abort()},[screen,selection,game]);
async function share(){if(!game)return;const squares=Array.from({length:game.totalHints},(_,i)=>i===game.stage?(game.status==='won'?'🟩':'🟥'):i<game.stage?'⬛':'⬜').join('');const text=`KnowBalledge ⚽\n${selection.season==='every'?'Every Season':selection.season} • ${selection.category}\n${squares}\nScore: ${game.score}\n${location.origin}`;try{await navigator.clipboard.writeText(text);setCopied(true);setTimeout(()=>setCopied(false),2000)}catch{setError('Couldn’t copy automatically. Select and copy this result: '+text)}}
const eras=selection.season==='every'?'Every Season':selection.season;const title=screen==='season'?'CHOOSE YOUR ERA':screen==='mode'?'CHOOSE YOUR CHALLENGE':selection.mode==='league'?'CHOOSE A LEAGUE':'CHOOSE A COUNTRY';
return <main className={`app-shell ${screen==='home'?'on-home':'in-menu'} ${reduced?'reduce-motion':''}`}><div className="stadium-bg"/><div className="atmosphere"/><div className="grain"/>
<header className="game-header"><button className="brand-button" onClick={()=>navigate('home')} aria-label="KnowBalledge home"><span className="brand-monogram">K<span>B</span></span><Logo/></button><div className="header-right"><button className="how-to" onClick={()=>setHelp(true)}><HelpCircle size={16}/> How to play</button><span className="header-divider"/><button className="icon-button" aria-label={soundOn?'Mute sound':'Enable sound'} onClick={()=>{remember('kb-sound',!soundOn);setSoundOn(!soundOn);sound('click',!soundOn)}}>{soundOn?<Volume2 size={20}/>:<VolumeX size={20}/>}</button><button className="icon-button" aria-label="Settings" onClick={()=>setSettings(true)}><Settings2 size={20}/></button></div></header>
{screen==='home'?<section className="title-screen screen-enter"><div className="title-eyebrow"><span/> THE BEAUTIFUL GAME. THE ULTIMATE GUESS.</div><h1 className="hero-brand"><Logo large/></h1><p className="tagline">How well do you really know football?</p><div className="play-block"><button className="play-button" aria-label="Play KnowBalledge" onClick={()=>{sound('click',soundOn);go('season')}}><Play size={42} fill="currentColor" strokeWidth={1.5}/></button><span className="play-caption">LET’S FIND OUT</span></div><div className="home-rules"><span>ONE PLAYER</span><i/><span>FIVE CLUES</span><i/><span>ALL FOOTBALL</span></div><button className="home-help" onClick={()=>setHelp(true)}>New to the game? <span>Here’s the game plan <ArrowRight size={14}/></span></button><div className="home-bottom"><span><ShieldCheck size={15}/> NO SIGN-UP TO PLAY</span><div className="edition"><span className="live-dot"/> {catalog?.dataMode==='verified'?'MATCH READY':'DEMO EDITION'}</div><span>KNOW BALL. PROVE IT.</span></div></section>:null}
{['season','mode','category'].includes(screen)&&<section className="menu-screen screen-enter" key={screen}><div className="menu-navigation"><button className="back-button" onClick={()=>navigate(screen==='season'?'home':screen==='mode'?'season':'mode')}><ArrowLeft size={17}/> BACK</button><div className="step-indicator"><span className="active">01 <small>ERA</small></span><ChevronRight size={12}/><span className={screen!=='season'?'active':''}>02 <small>CHALLENGE</small></span><ChevronRight size={12}/><span className={screen==='category'?'active':''}>03 <small>KICK-OFF</small></span></div><span className="menu-meta">{screen==='season'?'THE ARCHIVES':eras}</span></div><div className="section-heading"><p className="eyebrow">{screen==='season'?'EVERY GREAT PLAYER HAS AN ERA':screen==='mode'?'TWO WAYS TO PROVE YOU KNOW BALL':eras+' / '+selection.mode.toUpperCase()+' MODE'}</p><h1>{title}<span>.</span></h1><p>{screen==='season'?'Pick a season. Step back onto the pitch.':screen==='mode'?'Club football or national pride. Where’s your expertise?':selection.mode==='league'?'The biggest stages. The players you know.':'One nationality. A world of football talent.'}</p></div>
{screen==='season'&&<><button className="every-season" onClick={()=>{setSelection(s=>({...s,season:'every'}));navigate('mode')}}><div className="every-icon"><InfinityIcon size={44}/></div><div><span className="small-label">THE COMPLETE CHALLENGE</span><h2>EVERY SEASON</h2><p>A mystery era. An extra clue. Anything goes.</p></div><span className="card-tag">WILDCARD</span><ArrowRight className="every-arrow"/></button><div className="grid-label"><span>OR CHOOSE YOUR SEASON</span><span>2015 — 2027</span></div>{!catalog?<div className="inline-loader"><LoaderCircle className="spin"/> Checking the archives…</div>:<div className="season-grid">{catalog.seasons.map((s,i)=><button style={{animationDelay:`${i*25}ms`}} className={`season-card ${!s.available?'unavailable':''}`} key={s.name} disabled={!s.available} onClick={()=>{setSelection(p=>({...p,season:s.name}));navigate('mode')}}><div><span className="small-label">SEASON</span>{s.available?<ArrowRight size={16}/>:<LockKeyhole size={14}/>}</div><strong>{s.name.slice(2)}</strong><span className="season-caption">{!s.available?'Awaiting squad data':i===2?'BACK TO LAST SEASON':i>=8?'THE CLASSICS':'RELIVE THE SEASON'}</span></button>)}</div>}<p className="data-note">{catalog?.dataMode==='demo'?'Demo squads • 48 familiar names • 2015/16–2024/25. Newer seasons unlock when squad data is connected.':'Historical squad data • Players are matched to the selected season.'}</p></>}
{screen==='mode'&&<div className="mode-grid"><button className="mode-card league-mode" onClick={()=>{setSelection(s=>({...s,mode:'league'}));navigate('category')}}><span className="mode-number">01 / CLUB FOOTBALL</span><div className="mode-art"><Trophy size={105} strokeWidth={1}/></div><span className="small-label">FIVE ICONIC COMPETITIONS</span><h2>LEAGUE</h2><p>From the Premier League to LaLiga.<br/>Your league. Your home advantage.</p><div className="mode-footer"><span>CHOOSE YOUR LEAGUE</span><ArrowRight/></div></button><button className="mode-card country-mode" onClick={()=>{setSelection(s=>({...s,mode:'country'}));navigate('category')}}><span className="mode-number">02 / NATIONAL PRIDE</span><div className="mode-art"><Globe2 size={112} strokeWidth={1}/></div><span className="small-label">TWELVE FOOTBALL NATIONS</span><h2>COUNTRY</h2><p>Follow the flag across club borders.<br/>How well do you know your nation?</p><div className="mode-footer"><span>CHOOSE YOUR COUNTRY</span><ArrowRight/></div></button></div>}
{screen==='category'&&(busy?<div className="inline-loader"><LoaderCircle className="spin"/> Checking the squad…</div>:<div className={selection.mode==='league'?'league-grid':'country-grid'}>{(selection.mode==='league'?leagues.map(l=>({name:l.name,code:l.code,sub:l.country,color:l.color})):countries.map(c=>({name:c[0],code:c[1],sub:'NATIONALITY',color:'#b8ed78'}))).map((c,i)=><button key={c.name} className="category-card" style={{'--league-color':c.color,animationDelay:`${i*35}ms`} as React.CSSProperties} disabled={!counts[c.name]} onClick={()=>start({...selection,category:c.name})}><FlagMark code={c.code}/><span className="small-label">{c.sub}</span><h2>{c.name}</h2><div><span>{counts[c.name]?'KICK OFF':'NO SQUAD THIS SEASON'}</span><ArrowRight size={18}/></div></button>)}</div>)}
{error&&<div className="error-inline" role="alert">{error}<button onClick={()=>{void loadCatalog();if(screen==='category'){setScreen('mode')}}}>RETRY</button></div>}</section>}
{screen==='loading'&&<section className="loading-screen screen-enter"><div className="loading-symbol"><Target size={76} strokeWidth={1.2}/></div><span className="eyebrow">SCOUTING REPORT</span><h1>FINDING YOUR<br/>MYSTERY PLAYER<span>.</span></h1><p>Checking the squad. Studying the tactics.</p><div className="loading-dots"><i/><i/><i/></div></section>}
{screen==='game'&&game&&<section className="match-screen screen-enter"><div className="match-top"><button className="back-button" onClick={()=>navigate('category')}><ArrowLeft size={17}/> LEAVE MATCH</button><div className="match-selection"><span><CalendarDays size={15}/>{eras}</span><span>{selection.category}</span></div><div className="points-available"><Trophy size={16}/><b>{(game.totalHints-game.stage)*200+(game.attempts===0?100:0)}</b> <span>PTS AVAILABLE</span></div></div><div className="match-heading"><span className="eyebrow">THE SCOUTING REPORT</span><h1>WHO’S THE PLAYER<span>?</span></h1></div><ProgressBar hints={game.hints} total={game.totalHints} stage={game.stage}/><div className="match-layout"><aside className="unlocked-clues"><span className="small-label">YOUR INTEL</span>{game.hints.slice(0,-1).map(h=><div key={h.type}><small>{h.type}</small><strong>{displayHint(h,imperial)}</strong></div>)}{game.hints.length===1&&<p>Every clue brings<br/>you a little closer.</p>}<div className="scout-note"><Target size={18}/><span>Earlier guesses.<br/>Bigger bragging rights.</span></div></aside><div className="main-clue"><HintCard key={game.stage} hint={game.hints.at(-1)!} index={game.stage} imperial={imperial}/><div className="attempts"><span className={game.attempts>0?'used':''}/><span/>{2-game.attempts} {game.attempts?'GUESS':'GUESSES'} LEFT FOR THIS CLUE</div></div><aside className="guess-history"><span className="small-label">YOUR GUESSES <small>{game.history.length.toString().padStart(2,'0')}</small></span>{game.history.length===0?<p>A clean sheet.<br/>Make your first move.</p>:<ol>{game.history.slice().reverse().map((h,i)=><li key={i}><X size={13}/>{h.name}</li>)}</ol>}</aside></div><div className={`feedback ${notice.startsWith('Not')?'wrong':''}`} key={game.version} role="status">{error||notice||'Your first clue is in. Who comes to mind?'}</div><PlayerSearch onGuess={submit} disabled={busy} reset={reset}/><div className="match-bottom"><span><LockKeyhole size={13}/> IDENTITY HIDDEN UNTIL THE FINAL WHISTLE</span><button onClick={()=>setHelp(true)}>Need the rules? <HelpCircle size={14}/></button></div></section>}
{screen==='result'&&game?.player&&<section className="result-screen screen-enter">{game.status==='won'&&<div className="confetti" aria-hidden="true">{Array.from({length:28},(_,i)=><i key={i} style={{left:`${(i*37)%100}%`,animationDelay:`${i%5*.15}s`,'--turn':`${i*48}deg`} as React.CSSProperties}/>)}</div>}<p className="eyebrow">{game.status==='won'?'FULL-TIME. FULL MARKS FOR FOOTBALL KNOWLEDGE.':'THE FINAL WHISTLE'}</p><h1>{game.status==='won'?'YOU GOT IT':'THE PLAYER WAS'}<span>{game.status==='won'?'!':'…'}</span></h1><div className={`result-card ${game.status==='won'?'winner':''}`}><div className="player-portrait">{game.player.imageUrl&&!imageFailed?<img src={game.player.imageUrl} alt={game.player.name} onError={()=>setImageFailed(true)}/>:<UserRound size={128} strokeWidth={.75}/>}<span>{game.status==='won'?<Check size={24}/>:<Flag size={24}/>}</span></div><div className="result-name"><span className="small-label">MYSTERY PLAYER REVEALED</span><h2>{game.player.name}</h2><p>{game.player.club} <span>•</span> {game.player.season}</p></div><div className="player-facts"><div><span>NATIONALITY</span><strong>{game.player.nationality}</strong></div><div><span>POSITION</span><strong>{game.player.position}</strong></div><div><span>HEIGHT</span><strong>{displayHint({type:'Height',value:String(game.player.heightCm)},imperial)}</strong></div><div><span>WEIGHT</span><strong>{displayHint({type:'Weight',value:String(game.player.weightKg)},imperial)}</strong></div></div><div className="result-score"><div><Trophy size={21}/><span>{game.status==='won'?'WELL PLAYED':'THAT ONE WAS TOUGH'}</span></div><strong>{countedScore.toLocaleString()} <small>PTS</small></strong><p>{game.status==='won'?`Solved on clue ${game.stage+1} of ${game.totalHints}. That’s knowing ball.`:'Even the best miss a sitter. Go again?'}<br/><span>PERSONAL BEST · {best.toLocaleString()} PTS</span></p></div></div><div className="result-actions"><button className="primary-button" onClick={()=>start()}><RotateCcw size={18}/>{game.status==='won'?'PLAY AGAIN':'TRY ANOTHER'}</button><button className="outline-button" onClick={share}>{copied?<Check size={17}/>:<Copy size={17}/>} {copied?'COPIED!':'SHARE RESULT'}</button></div><div className="result-links"><button onClick={()=>navigate('season')}>Change season</button><i/><button onClick={()=>navigate('mode')}>Change mode</button><i/><button onClick={()=>navigate('home')}>Home</button></div>{error&&<p className="error-inline">{error}</p>}</section>}
{screen==='error'&&<section className="loading-screen"><Target size={65}/><h1>VAR CHECK FAILED<span>.</span></h1><p>{error||'We couldn’t load player data. Try again.'}</p><button className="primary-button" onClick={()=>start()}>RETRY <RotateCcw size={18}/></button><button className="text-button" onClick={()=>navigate('season')}>Choose another season</button></section>}
{screen!=='home'&&<footer className="site-footer"><span>KNOW BALL. PROVE IT.</span><span>{catalog?.dataMode==='verified'?'HISTORICAL SQUADS':'DEMO EDITION'} <i/> KNOWBALLEDGE</span></footer>}
<Dialog open={settings} onOpenChange={setSettings}><DialogContent className="game-dialog"><span className="eyebrow">MAKE IT YOUR GAME</span><DialogTitle>SETTINGS</DialogTitle><DialogDescription>A few adjustments before kick-off.</DialogDescription><div className="setting-row"><label htmlFor="sound-setting">Match sounds<small>Clicks, clues and celebrations</small></label><Switch id="sound-setting" checked={soundOn} onCheckedChange={v=>{setSoundOn(v);remember('kb-sound',v)}}/></div><div className="setting-row"><label htmlFor="motion-setting">Reduced motion<small>A calmer match experience</small></label><Switch id="motion-setting" checked={reduced} onCheckedChange={v=>{setReduced(v);remember('kb-motion',v)}}/></div><div className="setting-row"><label htmlFor="unit-setting">Imperial units<small>{imperial?'Feet, inches and pounds':'Centimetres and kilograms'}</small></label><Switch id="unit-setting" checked={imperial} onCheckedChange={v=>{setImperial(v);remember('kb-imperial',v)}}/></div></DialogContent></Dialog>
<Dialog open={help} onOpenChange={setHelp}><DialogContent className="game-dialog help-dialog"><span className="eyebrow">THE GAME PLAN</span><DialogTitle>FIVE CLUES. ONE PLAYER.</DialogTitle><DialogDescription>Pick an era and a league or nationality, then identify the mystery player.</DialogDescription><ol className="rules-list"><li><b>01</b><div><strong>Read the clues.</strong><p>Nationality → League → Position → Height → Weight. Every Season starts with an extra season clue.</p></div></li><li><b>02</b><div><strong>Take your two shots.</strong><p>You get two guesses per clue. Select a player from autocomplete. Two misses unlock the next clue.</p></div></li><li><b>03</b><div><strong>Know it early. Score big.</strong><p>Standard clues score 1,000 / 800 / 600 / 400 / 200 points. Add 100 for the first attempt at a clue. Every Season begins at 1,200.</p></div></li></ol><div className="demo-disclosure"><strong>{catalog?.dataMode==='verified'?'Historical player data':'You’re playing the demo edition.'}</strong><p>{catalog?.dataMode==='verified'?'Club and league refer to the selected season. Physical measurements are profile values.':'48 famous players across 2015/16–2024/25. Club spells are season-specific; height and weight are illustrative profile values. 2025/26 and 2026/27 await imported squads. Player portraits appear when licensed images are available.'}</p></div><button className="primary-button" onClick={()=>setHelp(false)}>GOT IT <Check size={18}/></button></DialogContent></Dialog>
<AlertDialog open={leave!==null} onOpenChange={v=>{if(!v)setLeave(null)}}><AlertDialogContent className="game-dialog"><AlertDialogTitle>LEAVE THIS GAME?</AlertDialogTitle><AlertDialogDescription>Your current progress will be lost.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Keep playing</AlertDialogCancel><AlertDialogAction onClick={()=>{if(leave)go(leave);setLeave(null)}}>Leave game</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
</main>}
