"use client";
import {useEffect,useState} from 'react';
import {Search,ArrowRight} from 'lucide-react';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
export type Candidate={id:string;name:string};
export function PlayerSearch({onGuess,disabled,reset}:{onGuess:(p:Candidate)=>void;disabled:boolean;reset:number}){const [query,setQuery]=useState(''),[items,setItems]=useState<Candidate[]>([]),[pick,setPick]=useState<Candidate|null>(null),[issue,setIssue]=useState(''),[loading,setLoading]=useState(false),[open,setOpen]=useState(false);
useEffect(()=>{setQuery('');setPick(null);setItems([]);setIssue('');setOpen(false)},[reset]);
useEffect(()=>{if(!query.trim()){setItems([]);return;}const ctrl=new AbortController();const t=setTimeout(async()=>{setLoading(true);setIssue('');try{const r=await fetch('/api/players?q='+encodeURIComponent(query),{signal:ctrl.signal});if(!r.ok)throw Error();setItems(await r.json());}catch{if(!ctrl.signal.aborted)setIssue('Search unavailable. Please try again.')}finally{if(!ctrl.signal.aborted)setLoading(false)}},120);return()=>{clearTimeout(t);ctrl.abort()}},[query]);
function submit(){const p=pick??items.find(x=>x.name.toLowerCase()===query.toLowerCase());if(p)onGuess(p);else setIssue('Choose a player from the suggestions first.');}
return <div className="guess-area"><label className="small-label" htmlFor="player-search">WHO’S YOUR GUESS?</label><form className="guess-form" onSubmit={e=>{e.preventDefault();submit()}}><Search className="search-icon" size={21}/><Combobox open={open} onOpenChange={setOpen} items={items} value={pick} onValueChange={v=>{setPick(v);if(v){setQuery(v.name);setOpen(false)}}} inputValue={query} onInputValueChange={(v,details)=>{setQuery(v);if(details.reason==='input-change'){setOpen(!!v.trim());if(pick&&v!==pick.name)setPick(null)}}} itemToStringLabel={p=>p.name} filter={null}><ComboboxInput id="player-search" aria-label="Player name" placeholder="Type a player’s name…" showTrigger={false} disabled={disabled} autoComplete="off"/><ComboboxContent className="player-options"><ComboboxEmpty>{loading?'Scouting players…':issue||'No player found. Try another name.'}</ComboboxEmpty><ComboboxList>{(p:Candidate)=><ComboboxItem key={p.id} value={p}>{p.name}</ComboboxItem>}</ComboboxList></ComboboxContent></Combobox><button className="submit-guess" disabled={disabled||!query.trim()} type="submit">GUESS <ArrowRight size={19}/></button></form>{issue&&<p className="search-issue" role="status">{issue}</p>}<p className="input-tip">Select a name from the list. Trust your football instinct.</p></div>}
